### ISSUE TITLE
Specify version of aide_design/python

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/Textbook#13]
We need to tell the textbook consumers what versions of python and aide_design we are using. Include this when we are easing the readers into python, probably into the intro structure.

**Comment by ethan92429** [comment]
Note that Travis, since it is running all your tests, will need to also know the versions. Basically, the environment that Travis tests the textbook in is also the environment in which the students will want to work in. It is guaranteed to work in the Travis environment (because it did when you pushed!)

**Comment by juanchon998** [comment]
@monroews @clare45 what versions of python are you using? Right now mine is 3.6.3, but I will not be writing too much python.

**Comment by clare45** [comment]
I'm on 3.6.5

**Comment by juanchon998** [comment]
Software versions are specified in a table at the beginning of the index.
