### ISSUE TITLE
Can't publish release 0.0.14

### ISSUE THREAD

**Issue by monroews** [AguaClara/Textbook#95]
We are stuck on release 0.0.8. I thought I did everything necessary to release version 0.0.14, but it isn't publishing and I'm clearly missing the last? step.

**Comment by juanchon998** [comment]
This was solved by Monroe. The problem was that the pdf was not being compiled correctly due to errors in the :math: directive. Monroe fixed them all when he released version 0.0.16.

@ethan92429 , can you please add to [this section](https://aguaclara.github.io/Textbook/Textbook_Creation_Help/rst_intro.html#building-rst-locally-with-sphinx) in the textbook with a snippet about how to build the pdf locally?

**Comment by juanchon998** [comment]
@monroews 

Can you share what the main problems were with the math formatting so that we can avoid them in the future?

**Comment by monroews** [comment]
It turned out to be a missing { in an equation. But I think we should format our rst documents so they display correctly in the preview so we have an instant check.  For example, there must be a carriage return after the figure declaration in order for the figure to display correctly. Similarly, there must be a carriage return after the math declaration before the equation.

**Comment by juanchon998** [comment]
email check!

Juan Guzmán

*EIT, Master of Engineering*
AguaClara Engineer

[image: https://www.aguaclarareach.org/] <https://www.aguaclarareach.org/>


On Tue, Aug 7, 2018 at 2:43 PM, Monroe Weber-Shirk <notifications@github.com

**Comment by monroews** [comment]
Don't worry about release 14. 16 is now live.

Monroe Weber-Shirk

AguaClara <http://aguaclara.cornell.edu/> Cornell
Civil and Environmental Engineering <http://www.cee.cornell.edu/>
Cornell University <http://www.cornell.edu/>
Hollister Hall 265
(607) 216-8445
